---  
  - name: install bacula-fd
    yum: name={{item}} state=present
    with_items:
      - bacula-client
      - bacula-console

  - service: name=bacula-fd state=stopped

  - name: config from template
    template:
      src: ../templates/bacula-fd.conf.j2
      dest: /etc/bacula/bacula-fd.conf

  - name: config from template
    template:
      src: ../templates/bconsole.conf.j2
      dest: /etc/bacula/bconsole.conf

  - service: name=bacula-fd state=started
