---
 - name: install nginx
   yum: name={{ item }} state=latest 
   with_items:
    - nginx

 - name: create nginx config file from template
   template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
   notify:
    - reload nginx
   tags:
    - nginx-configuration

 - name: restart nginx
   service: name=nginx state=restarted enabled=yes
