version: '2'

services:
  django:
    build: ./python
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./python:/code
    #ports:
    #  - 8082:8000
    networks:
      - node_network

  nodejs:
    image: "node:13"
    #user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./nodejs:/home/node/app
    #expose:
    #  - "8081"
    command: "npm install cross-env"
    command: "npm start"
    networks:
      - node_network


  #php:
  #  build: ./php
  #  ports:
  #    - 9999
  #  networks:
  #    - node_network

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 8081:8081
      - 8082:8082
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./php/wp:/var/www/html
    depends_on:
      - django
      - nodejs
    links:
      - wordpress
    networks:
      - node_network
    restart: always

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    #image: wordpress:5.3.2-php7.2-fpm
      #4.7.1-php7.0-fpm
    #ports:
    #  - '9000:9000'
    #ports:
    #  - 9000
    volumes:
      - ./php/wp:/var/www/html
    environment:
        - WORDPRESS_DB_NAME=wpdb
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_PASSWORD=aqwe123
    links:
        - mysql
    restart: always
    networks:
      - node_network

  mysql:
    image: mariadb
    ports:
        - '3306:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=aqwe123
    restart: always
    networks:
      - node_network

networks:
  node_network:
    driver: bridge
