---
 - name: Time access for nonadmin
   lineinfile: dest=/etc/security/time.conf
     insertafter=EOF
     line='login|sshd;*;{{ item.username }};!SaSu0000-2400'
     regexp='^{{ item.username }} .*'
     state=present
   when: item.group != 'admin'
   with_items: '{{users}}'

 - name: Add pam_time lib
   shell: find /etc/pam.d/ -type f | xargs sed -i 's/pam_nologin.so/pam_nologin.so\naccount\ required\ pam_time.so/g'
