---
 - name: install nfs-server
   yum: name={{ item }} state=latest
   with_items:
    - nfs-utils

 - name: create /etc/hosts from template
   template:
     src: exports.j2
     dest: /etc/exports

 - name: create nfs share dir
   file:
     path: /nfs
     state: directory
     mode: 0644

 - name: create nfs share dir
   file:
     path: /nfs/upload
     state: directory
     mode: 0666

# - name: Enable and start firewalld
#   systemd:
#     name: firewalld
#     enabled: yes
#     state: started

# - name: add services to firewall to public zone
#   firewalld:
#     service: "{{ item }}"
#     permanent: yes
#     state: enabled
#     zone: public
#   with_items:
#     - nfs
#     - rpc-bind
#     - mountd

# - name: Install - Configure firewalld
#   firewalld:
#     service: "{{ item }}"
#     permanent: yes
#     state: enabled
#     zone: public
#   with_items:
#     - ssh
#     - freeipa-ldap
#     - freeipa-ldaps
#     - nfs
#     - dns
#     - rpc-bind
#     - mountd

# - name: add ports
#   firewalld:
#     port: "{{ item }}"
#     permanent: yes
#     state: enabled
#     zone: public
#   with_items:
#     - 2049/tcp
#     - 2049/udp

# - name: restart firewall
#   service:
#     name: firewalld
#     state: restarted

 - name: Start nfs
   service:
     name: "{{ item }}"
     state: started
     enabled: yes
   with_items:
    - rpcbind
    - nfs-server
