
version: '3.3'
services:
  webserver:
      build: ./nginx
      ports:
          - "80:80"
      networks:
          - front
      volumes:
          - ./php:/code

  web:
    image: nginx
      ports:
          - 8001:80
      volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./conf/servers.conf:/etc/nginx/conf.d/servers.conf:ro
      command: [nginx-debug, '-g', 'daemon off;']
      depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
        - djangoapp
      networks:
          - nginx_network

  wp:
      image: wordpress
      command:
      ports:
        - "8081:8081"
      networks:
          - nginx_network

  djangoapp:
      build: ./django
      command:
      volumes:
        - .:/opt/services/djangoapp/src
      networks:
          - nginx_network

networks:
  nginx_network:
    driver: bridge
