---
- name: Ensure NFS utilities are installed.
  package: name=nfs-utils state=present

- name: Ensure rpcbind is running.
  service: name=rpcbind state=restarted enabled=yes

- name: Ensure /mnt/otus_share/ directory exists
  action: file path=/srv/ state=directory

- name: configure /etc/fstab on clients
  shell: echo "10.0.26.41:/srv/ /srv/ nfs rw,sync,nfsvers=3 0 0" >> /etc/fstab

- name: mount share
  shell: mount -a

