---
- name: install quagga
  hosts: all
  become: yes

  tasks:
    - include_vars: vars/main.yml

    - name: routing enable
      shell: /usr/sbin/sysctl -w net.ipv4.ip_forward=1 && /usr/sbin/sysctl -w net.ipv4.conf.all.rp_filter=0 && /usr/sbin/sysctl -p /etc/sysctl.conf

    - name: install quagga
      yum:
        name: quagga
        state: latest

    - name: copy ospf template
      template:
        src: ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf
      with_items: hosts.hostname.include_vars
#      when: hostname = r1 vars = srvr1
#      when: hostname = r2 vars = srvr2
#      when: hostname = r3 vars = srvr3
#      when: hostname = r4 vars = srvr4
      notify:
        - restart ospfd

    - name: copy zebra template
      template:
        src: zebra.conf.j2
        dest: /etc/quagga/zebra.conf
      with_items: "{{ hosts.hostname.include_vars }}"
#      when: hostname = r1 vars = srvr1
#      when: hostname = r2 vars = srvr2
#      when: hostname = r3 vars = srvr3
#      when: hostname = r4 vars = srvr4
      notify:
        - restart zebra


#  - nxos_interface_ospf:
#      interface: {{ item.interfaces }}
#      ospf: 1
#      area: {{ area }}
#      bfd: disable
#      cost: default
#      state: present
#    with_items:
#      - '{{ quagga }}'

  handlers:
    - name: restart zebra
      systemd:
        name: zebra
        state: started
        enabled: yes
      listen: restart zebra

    - name: restart ospfd
      systemd:
        name: ospfd
        state: started
        enabled: yes
