---
- name: install quagga
  hosts: quagga_routers
  become: yes

  tasks:
#  - include_vars: vars/main.yml

    - name: routing enable
      shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf && echo "net.ipv4.conf.eth*.rp_filter = 0" >> /etc/sysctl.conf && sysctl -p /etc/sysctl.conf

    - name: install quagga
      yum:
        name: quagga
        state: latest

    - name: copy zebra template
      template:
        src: zebra.conf.j2
        dest: /etc/quagga/zebra.conf
      notify:
        - restart zebra

    - name: copy ospf template
      template:
        src: ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf
      notify:
        - restart ospfd

#  - nxos_interface_ospf:
#      interface: {{ item.interfaces }}
#      ospf: 1
#      area: {{ area }}
#      bfd: disable
#      cost: default
#      state: present
#    with_items:
#      - '{{ quagga }}'

  handlers:
    - name: restart zebra
      systemd:
        name: zebra
        state: started
        enabled: yes
      listen: restart zebra

    - name: restart ospfd
      systemd:
        name: ospfd
        state: started
        enabled: yes
