---
- name: install quagga
  hosts: all
  become: yes

  tasks:

#    - name: routing enable
#      shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf && echo "net.ipv4.conf.all.rp_filter=0" >> /etc/sysctl.conf && sysctl -p /etc/sysctl.conf
#        /usr/sbin/sysctl -w net.ipv4.ip_forward=1 && /usr/sbin/sysctl -w net.ipv4.conf.all.rp_filter=0 && /usr/sbin/sysctl -p /etc/sysctl.conf

    - name: Enable forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - sysctl:
        name: net.ipv4.conf.all.forwarding
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: 0
        sysctl_set: yes
        state: present
        reload: yes

    - name: base packages install
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - net-tools
        - libsemanage-python
        - traceroute
        - tcpdump

    - name: install quagga
      yum:
        name: quagga
        state: latest

#    - name: del route default
#      shell: ip route del default

    - name: copy ospf template
      template:
        src: ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf
        owner: quagga
        group: quagga
        mode: 0644
      notify:
        - restart ospfd

    - name: copy zebra template
      template:
        src: zebra.conf.j2
        dest: /etc/quagga/zebra.conf
        owner: quagga
        group: quagga
        mode: 0644
      notify:
        - restart zebra

    - name: Restart network
      service:
        name: network
        state: restarted

  handlers:
    - name: restart zebra
      systemd:
        name: zebra
        state: started
        enabled: yes
      listen: restart zebra

    - name: restart ospfd
      systemd:
        name: ospfd
        state: started
        enabled: yes
