---

- name: Copying keepalived.conf
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: enable forwarding
  sysctl:
    name: net.ipv4.ip_nonlocal
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: enable forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
- name: restart network
  service: name=network state=restarted

#- name: Updating net.ipv4.ip_nonlocal_bind parameter
#  sudo: yes
#  lineinfile:
#    dest: /etc/sysctl.conf
#    line: 'net.ipv4.ip_nonlocal_bind=1'
#  shell: echo "net.ipv4.ip_nonlocal_bind=1" >> /etc/sysctl.conf

#- name: Updating net.ipv4.ip_forward parameter
#  sudo: yes
#  lineinfile:
#    dest: /etc/sysctl.conf
#    line: 'net.ipv4.ip_forward = 1'
#  echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf

#- name: Updating sysctl parameters
#  sudo: yes
#  shell: sysctl -p

- name: Enable keepalived to be started at boot
  service: name=keepalived enabled=yes state=started
