---
   - name: Enable forwarding
     sysctl:
       name: net.ipv4.ip_forward
       value: 1
       sysctl_set: yes
       state: present
       reload: yes

   - sysctl:
       name: net.ipv4.conf.all.forwarding
       value: 1
       sysctl_set: yes
       state: present
       reload: yes

   - sysctl:
       name: net.ipv4.conf.all.rp_filter
       value: 0
       sysctl_set: yes
       state: present
       reload: yes

   - name: Install quagga
     yum:
       name: quagga
       state: latest

   - name: Copy R1 config files
     block:
       - name: Your copy task
         copy: src={{ item.src }} dest={{ item.dest }}
         with_items:
           - { src: 'ospfd_R1.conf', dest: '/etc/quagga/ospfd.conf' }
           - { src: 'zebra-R1.conf', dest: '/etc/quagga/zebra.conf' }
           - { src: 'ifcfg-vlan10-R1', dest: '/etc/sysconfig/network-scripts/ifcfg-vlan10' }
           - { src: 'ifcfg-vlan30-R1', dest: '/etc/sysconfig/network-scripts/ifcfg-vlan30' }
     when: ansible_hostname == "R1"

   - name: Copy R2 config files
     block:
       - name: Your copy task
         copy: src={{ item.src }} dest={{ item.dest }}
         with_items:
           - { src: 'ospfd_R2.conf', dest: '/etc/quagga/ospfd.conf' }
           - { src: 'zebra-R2.conf', dest: '/etc/quagga/zebra.conf' }
           - { src: 'ifcfg-vlan10-R2', dest: '/etc/sysconfig/network-scripts/ifcfg-vlan10' }
           - { src: 'ifcfg-vlan20-R2', dest: '/etc/sysconfig/network-scripts/ifcfg-vlan20' }
     when: ansible_hostname == "R2"

   - name: Copy R3 config files
     block:
       - name: Your copy task
         copy: src={{ item.src }} dest={{ item.dest }}
         with_items:
           - { src: 'ospfd_R3.conf', dest: '/etc/quagga/ospfd.conf' }
           - { src: 'zebra-R3.conf', dest: '/etc/quagga/zebra.conf' }
           - { src: 'ifcfg-vlan30-R3', dest: '/etc/sysconfig/network-scripts/ifcfg-vlan30' }
           - { src: 'ifcfg-vlan20-R3', dest: '/etc/sysconfig/network-scripts/ifcfg-vlan20' }
     when: ansible_hostname == "R3"

   - name: change file ownership ospfd.conf
     file:
        path: /etc/quagga/ospfd.conf
        owner: quagga
        group: quagga
        
   - name: change file ownership zebra.conf
     file:
        path: /etc/quagga/zebra.conf
        owner: quagga
        group: quagga

   - name: Start and Enable zebra
     service:
       name: zebra
       state: started
       enabled: True

   - name: Change policy and state of SELinux
     selinux:
       state: disabled

   - name: Start and Enable ospfd
     service:
       name: ospfd
       state: started
       enabled: True

   - name: Restart network
     service:
       name: network
       state: restarted
