---
- name: install nmcli utils
  hosts: all
  become: true
  tasks:
    - name: install epel-release repository
      yum: name={{ item }} state=latest
      with_items:
       - epel-release
    - name: install network libs
      yum: name={{ item }} state=present
      with_items:
          - NetworkManager-glib
          - nm-connection-editor
          - libsemanage-python
          - policycoreutils-python
          - mc

- name: Enable ip forwarding
  hosts: routers
  become: true
  tasks:
    - name: Enable forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: restart network
      service: name=network state=restarted

- name: configure inetRouter
  hosts: inetRouter
  become: true
  tasks:
    - name: configure team0
      shell: |
        nmcli con add type team con-name team0 ifname team0
        nmcli con mod team0 team.config '{"device": "team0", "runner": {"name": "lacp", "active": true, "fast_rate": true, "tx_hash": ["eth", "ipv4", "ipv6"]}, "link_watch": {"name": "ethtool"}, "ports": {"eth1": {}, "eth2": {}}}'
        nmcli con mod team0 ipv4.addresses 192.168.255.1/24
        nmcli con mod team0 +ipv4.routes "10.10.10.0/24 192.168.255.2"
        nmcli con add type team-slave con-name team0-eth1 ifname eth1 master team0
        nmcli con add type team-slave con-name team0-eth2 ifname eth2 master team0
        nmcli con up team0-eth1
        nmcli con up team0-eth2
        nmcli con up team0
    - name: set iptables masquerade on inetRouter
      command: iptables -t nat -I POSTROUTING ! -d 10.10.10.0/24 -o eth0 -j MASQUERADE
    - name: set iptables masquerade on inetRouter
      command: iptables -t nat -I POSTROUTING ! -d 192.168.255.0/24 -o eth0 -j MASQUERADE

- name: configure centralRouter
  hosts: centralRouter
  become: true
  tasks:
    - name: configure team0
      shell: |
        nmcli device modify eth0 ipv4.never-default yes
        nmcli con add type team con-name team0 ifname team0 mode lacp ip4 192.168.255.2/24 gw4 192.168.255.1
        nmcli con add type team-slave con-name team0-eth1 ifname eth1 master team0
        nmcli con add type team-slave con-name team0-eth2 ifname eth2 master team0
        nmcli con up team0-eth1
        nmcli con up team0-eth2
        nmcli con up team0
        nmcli con add type vlan ifname VLAN100 dev eth3 id 100 ip4 10.10.10.10/24
        nmcli con add type vlan ifname VLAN101 dev eth3 id 101 ip4 10.10.10.11/24

- name: configure testClient1
  hosts: testClient1
  become: true
  tasks:
    - name: configure vlan and delete def route
      shell: |
        nmcli device modify eth0 ipv4.never-default yes
        nmcli con add type vlan ifname VLAN100 dev eth1 id 100 ip4 10.10.10.1/24 gw4 10.10.10.10

- name: configure testServer1
  hosts: testServer1
  become: true
  tasks:
    - name: configure vlan and delete def route
      shell: |
        nmcli device modify eth0 ipv4.never-default yes
        nmcli con add type vlan ifname VLAN100 dev eth1 id 100 ip4 10.10.10.254/24 gw4 10.10.10.10

- name: configure testClient1
  hosts: testClient2
  become: true
  tasks:
    - name: configure vlan and delete def route
      shell: |
        nmcli device modify eth0 ipv4.never-default yes
        nmcli con add type vlan ifname VLAN101 dev eth1 id 101 ip4 10.10.10.1/24 gw4 10.10.10.11

- name: configure testServer1
  hosts: testServer2
  become: true
  tasks:
    - name: configure vlan and delete def route
      shell: |
        nmcli device modify eth0 ipv4.never-default yes
        nmcli con add type vlan ifname VLAN101 dev eth1 id 101 ip4 10.10.10.254/24 gw4 10.10.10.11
