---
# playbook.yml file.
- hosts: all
  user: root
  become: true
  become_user: root
  roles:
    - os

- hosts: nfsservers
  user: root
  become: true
  become_user: root
  roles:
    - nfs-server

- hosts: backups
  user: root
  become: true
  become_user: root
  roles:
    - nfs-client

- hosts: dbs
  user: root
  become: true
  become_user: root
  roles:
    - XtraDB-Cluster
  vars:
   xtradb_bind_interface: eth1

- hosts: webservers
  vars_files:
    - group_vars/proxysql.yml
  user: root
  become: true
  become_user: root
  roles:
    - nginx
    - php-fpm
    - nfs-client
    - proxysql
    - wordpress

- hosts: lblservers
  user: root
  become: true
  become_user: root
  roles:
    - haproxy

- hosts: keepalived_master
  user: root
  become: true
  become_user: root
  roles:
    - keepalived
  vars:
    interface: eth1
    virtual_router_id: 1
    virtual_ipaddress: 10.0.26.81
    priority: 101
    secret_passwd: ZcnG9lGUoZeM3nFT

- hosts: keepalived_backup
  user: root
  become: true
  become_user: root
  roles:
    - keepalived
  vars:
    interface: eth1
    virtual_router_id: 1
    virtual_ipaddress: 10.0.26.81
    priority: 100
    secret_passwd: ZcnG9lGUoZeM3nFT
