version: '2'

services:
  wp:
    image: wordpress
    networks:
      - otus_network
    restart: always

  wiki:
    image: camandel/django-wiki
    networks:
      - otus_network
    restart: always

  nginx:
    image: nginx
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - wp
      - wiki
    networks:
      - otus_network

  #angular:
  #  image: angular/ngcontainer:0.2.0
  #  #ports:
  #  #  - 8082:80
  #  networks:
  #    - otus_network


networks:
  otus_network:
    driver: bridge
