---
#----------------------------------------------
- name: Ensure group "admin" exists
  group:
    name: admin
    state: present
- name: Ensure group "users" exists
  group:
    name: users
    state: present
#----------------------------------------------
#  - name: Add many users
#    user:
#     name: "{{ item.user}}"
#     shell: "{{ item.shell}}"
#     group: "{{ item.group}}"
#     password: "{{ item.password | password_hash('sha512') }}"
#    with_items:
#     - {user: 'first', shell: '/bin/bash', group: 'admin', password: 'first'}
#     - {user: 'second', shell: '/bin/bash', group: 'root', password: 'second'}
#     - {user: 'third', shell: '/bin/bash', group: 'users', password: 'third'}
#----------------------------------------------
- name: Add many users
  user:
    name: "{{ item.username}}"
    shell: "{{ item.shell}}"
    group: "{{ item.group}}"
    password: "{{ item.password | password_hash('sha512') }}"
    createhome: "{{ item.createhome }}"
  with_items:
    - '{{users}}'
