---
- name: epel
  yum:
    name: epel-release
    state: present

- name: install patroni requiered packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - python-devel
    - postgresql-devel
    - python2-pip

- name: add postgresql-11 repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: install postgresql-11
  yum:
    name: postgresql11-server
    state: present

- name: upgrade pip
  pip:
    name: pip
    state: forcereinstall

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - python-etcd
    - python-consul
    - psycopg2
    - psycopg2-binary
    - s3cmd
    - wheel
    - setuptools

- name: upgrade setuptools
  pip:
    name: setuptools
    state: forcereinstall

- name: install patroni
  pip:
    name: patroni
    state: present
  tags:
    - pip-patroni

- name: copy patroni systemd service file
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service

- name: create patroni directories
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  with_items:
      - /var/data/base
      - /etc/patroni/
  tags:
    - dirs

- name: cpy patroni config file
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml

- name: start patroni cluster
  systemd:
    name: patroni
    state: restarted
    daemon_reload: True
    enabled: true

- name: place bashrc file
  template:
    src: bashrc.j2
    dest: /root/.bashrc
