# - name: Sshd update conf
#   lineinfile:
#     path: /etc/ssh/sshd_config
#     insertafter: EOF
#     regexp: 'PasswordAuthentication\ no'
#     line: 'PasswordAuthentication\ yes'
#     state: present
#   notify:
#   - restart sshd
---
 - name: sshd password autentefication 
   lineinfile: dest=/etc/ssh/sshd_config
     regexp='#Port 22'
     line='Port 22'
   notify:
     - restart sshd

 - name: sshd password autentefication 
   lineinfile: dest=/etc/ssh/sshd_config
     regexp='PasswordAuthentication no'
     line='PasswordAuthentication yes'
   notify:
     - restart sshd
