---
 - name: sshd port 22
   lineinfile: dest=/etc/ssh/sshd_config
     regexp='#Port 22'
     line='Port 22'
   notify:
     - restart sshd

 - name: sshd password autentefication 
   lineinfile: dest=/etc/ssh/sshd_config
     regexp='PasswordAuthentication no'
     line='PasswordAuthentication yes'
   notify:
     - restart sshd
