version: '2'

services:
  database1:
    image: postgres:10
    volumes:
      - database1_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database1_env
    networks:
      - database1_network

  database2:
    image: postgres:10
    volumes:
      - database2_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database2_env
    networks:
      - database2_network

  djangoapp:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/djangoapp/src
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - database1_network
      - database2_network
      - nginx_network
    depends_on:
      - database1
      - database2

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 8080:8080
      - 8888:8888
      - 9999:9999
    volumes:
      - ./config/nginx:/etc/nginx
    #  - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
      - ./html:/var/www/html
    #  - ./app:/src/app
    #volumes_from:
    #  - wordpress
    #  - node
    networks:
      - nginx_network
      - wp_network
      - node_network
    depends_on:
      - djangoapp
      - wordpress
    links:
      - wordpress

  mysql:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    networks:
      - wp_network
    restart: always

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - ./html:/var/www/html
    networks:
      - wp_network
    depends_on:
      - mysql
    #ports:
    #  - 9000
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always

  node:
    image: node:latest
    volumes:
      - ./app:/src/app
    ports:
      - 3000
    command: npm start
    networks:
      - node_network

networks:
  database1_network:
    driver: bridge
  database2_network:
    driver: bridge
  nginx_network:
    driver: bridge
  wp_network:
    driver: bridge
  node_network:
    driver: bridge

volumes:
  database1_volume:
  database2_volume:
  static:
  media:
  www:
