---

# Servers of PGSQL Masters
- hosts: nfssrv
  become: yes
  roles:
          #    - { role: CentOS_Srv }
          - { role: nfs_srv }

# Servers of PGSQL Slaves
- hosts: nfsclient
  become: yes
  roles:
          #    - { role: CentOS_Srv }
          - { role: nfs_client }
