---
 - name: copy elasticsearch.repo
   copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

 - name: install elasticsearch
   yum: name={{ item }} state=latest
   with_items:
    - java-1.8.0-openjdk
    - elasticsearch
    - kibana
    - logstash

 - name: copy elasticsearch.yml
   copy: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml

 - name: copy kibana.yml
   copy: src=kibana.yml dest=/etc/kibana/kibana.yml

 - file:
    path: /etc/logstash/
    state: directory
    mode: 0755

 - name: copy logstash.yml
   copy: src=jvm.options dest=/etc/logstash/jvm.options

 - name: intstall logstash
   shell: /usr/share/logstash/bin/./system-install

 - name: copy input.conf
   copy: src=input.conf dest=/etc/logstash/conf.d/input.conf

 - name: copy output.conf
   copy: src=output.conf dest=/etc/logstash/conf.d/output.conf

 - name: copy filter.conf
   copy: src=filter.conf dest=/etc/logstash/conf.d/filter.conf

 - name: restart elasticsearch
   service: name=elasticsearch state=restarted enabled=yes

 - name: restart kibana
   service: name=kibana state=restarted enabled=yes

 - name: restart logstash
   service: name=logstash state=restarted enabled=yes